from django.urls import path
from . import views

urlpatterns = [
    path("tour_list/", views.tour_list, name="tour_list"),
    path("tour/<int:pk>/", views.tour_detail, name="tour_detail"),
    path("tour_create/", views.tour_create, name="tour_create"),
    path("tour/<int:pk>/edit/", views.tour_update, name="tour_update"),
    path("tour/<int:pk>/delete/", views.tour_delete, name="tour_delete"),
    path("destination_list/", views.destination_list, name="destination_list"),
    path("destination/<int:pk>/", views.destination_detail, name="destination_detail"),
    path("destination_create/", views.destination_create, name="destination_create"),
    path("todestination/<str:name>/edit/", views.destination_update,  name="destination_update"),
    path("destination/<int:pk>/delete/", views.destination_delete, name="destination_delete"),
    path('esewaform/', views.EsewaView.as_view(), name="esewaform"),
    path('esewaverify/<int:tour_id>/<int:booking_id>', views.esewa_verify, name="esewaverify"),
    path("booktour/<int:tour_id>/", views.book_tour, name="booktour"),
    path("user/", views.user, name="user"),
    path('gallery_list/', views.gallery_list, name='gallery_list'),
    path('gallery_form/', views.gallery_form, name="gallery_form"),
    path('gallery_delete/<int:pk>/delete/', views.gallery_delete, name="gallery_delete"),
    path("about_us_list/", views.about_list, name="about_us_list"),
    path("about_us_create/", views.about_form, name="about_us_create"),
    path("about_us/<int:pk>/edit/", views.about_update, name="about_us_update"),
    path("about_us/<int:pk>/delete/", views.about_delete, name="about_us_delete"),
    path('mybook/<int:tour_id>/', views.my_book, name="mybook"),
    path("deletebook/<int:book_id>", views.remove_book_item, name='removebook'),
    path("home_list/", views.home_list, name="home"),
    path("homepage_create/", views.homepages_form, name="homepage_create"),
    path("homepage/<int:pk>/edit/", views.homepage_update, name="homepage_update"),
    # path("user/", views.user, name="user"),
    path("booking", views.booking, name="booking"),
    path("addfavoriteplace/<int:tour_id>/", views.add_to_favoriteplace, name="addfavoriteplace"),
    path("removefavoriteplace/<int:book_id>/", views.remove_favoriteplace_item, name="removefavoriteplace"),
]
