# Generated by Django 5.0.6 on 2024-07-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publice', '0006_about_us_alter_booking_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_us',
            old_name='department',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='about_us',
            old_name='position',
            new_name='team',
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('Cash on delivery', 'Cash on delivery'), ('Esewa', 'Esewa')], max_length=200, null=True),
        ),
    ]
