# Generated by Django 5.0.6 on 2024-07-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publice', '0007_rename_department_about_us_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('Esewa', 'Esewa'), ('Cash on delivery', 'Cash on delivery')], max_length=200, null=True),
        ),
    ]
