# Generated by Django 5.0.6 on 2024-07-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publice', '0009_alter_booking_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='image',
            field=models.ImageField(upload_to='static/about_us'),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('Esewa', 'Esewa'), ('Cash on delivery', 'Cash on delivery')], max_length=200, null=True),
        ),
    ]
