# Generated by Django 5.0.6 on 2024-07-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publice', '0011_alter_booking_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='team',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('Esewa', 'Esewa'), ('Cash on delivery', 'Cash on delivery')], max_length=200, null=True),
        ),
    ]
