# Generated by Django 5.0.6 on 2024-07-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publice', '0012_alter_about_us_team_alter_booking_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/bg')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('Cash on delivery', 'Cash on delivery'), ('Esewa', 'Esewa')], max_length=200, null=True),
        ),
    ]
