# Generated by Django 5.0.6 on 2024-07-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publice', '0013_homepage_alter_booking_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.IntegerField()),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('fblink', models.TextField()),
                ('twlink', models.TextField()),
                ('ytlink', models.TextField()),
            ],
        ),
    ]
