# Generated by Django 5.0.6 on 2024-07-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publice', '0014_navebar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('Esewa', 'Esewa'), ('Cash on delivery', 'Cash on delivery')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='navebar',
            name='logo',
            field=models.ImageField(blank=True, upload_to='static/bg'),
        ),
    ]
