# Generated by Django 5.0.6 on 2024-07-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publice', '0020_rename_book_date_booking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
