# Generated by Django 5.0.6 on 2024-08-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publice', '0021_profile_firstname_profile_lastname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Navebar',
        ),
        migrations.AlterField(
            model_name='booking',
            name='num_travelers',
            field=models.IntegerField(null=True),
        ),
    ]
